### ISSUE TITLE
Can't build from master branch

### ISSUE THREAD

**Issue by KnightBaron** [arauchfuss/Simple-Comic#84]
First of all, thank you for this wonderful application. I use it all the time.

I'm on OS X 10.8.4 with Xcode 4.6.3 . I'm trying to build Simple Comic straight from master branch (To be specific, this commit. 87a696fd7d08d5ac50183b67d6671b9ae1ded950 ) but I got the following error.

```
/Users/knightbaron/Projects/Simple-Comic/Session/TSSTThumbnailView.m:257:24: error: bad receiver type 'id'
    NSImage * thumb = [[pageController arrangedObjects][index] valueForKey: @"pageImage"];
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/Session/TSSTThumbnailView.m:262:32: error: bad receiver type 'id'
    thumbnailView.imageName = [[pageController arrangedObjects][index] valueForKey: @"name"];
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

My guess is that it may have something to do with build configuration but I don't really know much about Objective-C stuffs. After fiddling with build configuration randomly, now I got this.

```
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:182:18: error: array subscript is not an integer
        standardDefaults[TSSTPageOrder] = @NO;
                        ^~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:183:18: error: array subscript is not an integer
        standardDefaults[TSSTPageZoomRate] = @0.1f;
                        ^~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:184:18: error: array subscript is not an integer
        standardDefaults[TSSTPageScaleOptions] = @1;
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:185:21: error: array subscript is not an integer
    standardDefaults[TSSTThumbnailSize] = @100;
                    ^~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:186:21: error: array subscript is not an integer
    standardDefaults[TSSTTwoPageSpread] = @YES;
                    ^~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:187:21: error: array subscript is not an integer
    standardDefaults[TSSTIgnoreDonation] = @NO;
                    ^~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:188:21: error: array subscript is not an integer
    standardDefaults[TSSTConstrainScale] = @YES;
                    ^~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:189:21: error: array subscript is not an integer
    standardDefaults[TSSTScrollersVisible] = @YES;
                    ^~~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:190:21: error: array subscript is not an integer
    standardDefaults[TSSTSessionRestore] = @YES;
                    ^~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:191:21: error: array subscript is not an integer
    standardDefaults[TSSTAutoPageTurn] = @YES;
                    ^~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:192:18: error: array subscript is not an integer
        standardDefaults[TSSTBackgroundColor] = [NSArchiver archivedDataWithRootObject: [NSColor whiteColor]];
                        ^~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:193:21: error: array subscript is not an integer
    standardDefaults[TSSTWindowAutoResize] = @YES;
                    ^~~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:194:21: error: array subscript is not an integer
    standardDefaults[TSSTLoupeDiameter] = @500;
                    ^~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:195:18: error: array subscript is not an integer
        standardDefaults[TSSTLoupePower] = @2.0f;
                        ^~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:196:19: error: array subscript is not an integer
        standardDefaults[TSSTStatusbarVisible] = @YES;
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:197:21: error: array subscript is not an integer
    standardDefaults[TSSTLonelyFirstPage] = @YES;
                    ^~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:198:18: error: array subscript is not an integer
        standardDefaults[TSSTNestedArchives] = @YES;
                        ^~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:199:18: error: array subscript is not an integer
        standardDefaults[TSSTUpdateSelection] = @0;
                        ^~~~~~~~~~~~~~~~~~~~
/Users/knightbaron/Projects/Simple-Comic/SimpleComicAppDelegate.m:526:47: error: incompatible operand types ('NSArray' and 'NSString *')
    NSString * basePath = ([paths count] > 0) ? paths[0] : NSTemporaryDirectory();
                                              ^ ~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by arauchfuss** [comment]
SC compiles with Xcode 8.2 at this time.
